Repository victoricoma/helpr, pull requests merged in 2022-06, with the labels that each got.

#51 Adição via Post das informações de tecnico.
  src/main/java/com/api/helpr/domain/Tecnico.java
  src/main/java/com/api/helpr/resources/TecnicoResource.java
  src/main/java/com/api/helpr/services/TecnicoService.java
Labels: documentation, enhancement

#54 Criação do update do banco via PUT e com as validações.
  src/main/java/com/api/helpr/domain/Pessoa.java
  src/main/java/com/api/helpr/resources/TecnicoResource.java
  src/main/java/com/api/helpr/services/TecnicoService.java
Labels: documentation, enhancement

#55 Recurso de delete com uso de log para update no banco.
  MySQL/script_helpr/log_pessoa_gt.sql
  src/main/java/com/api/helpr/resources/TecnicoResource.java
  src/main/java/com/api/helpr/services/TecnicoService.java
Labels: documentation, enhancement

#74 Busca um chamado via ID no banco.
  src/main/java/com/api/helpr/domain/dtos/ChamadoDTO.java
  src/main/java/com/api/helpr/resources/ChamadoResource.java
  src/main/java/com/api/helpr/services/ChamadoService.java
Labels: documentation, enhancement

#76 RestController para listagem geral de Chamados
  src/main/java/com/api/helpr/resources/ChamadoResource.java
  src/main/java/com/api/helpr/services/ChamadoService.java
Labels: documentation, enhancement

#77 Adição das validações de chamado e inserção via front POST.
  src/main/java/com/api/helpr/domain/dtos/ChamadoDTO.java
  src/main/java/com/api/helpr/resources/ChamadoResource.java
  src/main/java/com/api/helpr/services/ChamadoService.java
Labels: documentation, enhancement

#78 Correções de domínio e dto de chamado e update de chamado.
  src/main/java/com/api/helpr/domain/Chamado.java
  src/main/java/com/api/helpr/domain/dtos/ChamadoDTO.java
  src/main/java/com/api/helpr/resources/ChamadoResource.java
  src/main/java/com/api/helpr/services/ChamadoService.java
Labels: documentation, enhancement

#79 Configuração de testes de segurança
  pom.xml
  src/main/java/com/api/helpr/config/SecurityConfig.java
  src/main/java/com/api/helpr/domain/dtos/CredenciaisDTO.java
  src/main/java/com/api/helpr/security/JWTUtil.java
  src/main/java/com/api/helpr/security/UserSS.java
  src/main/java/com/api/helpr/services/ClienteService.java
  src/main/java/com/api/helpr/services/DBService.java
  src/main/java/com/api/helpr/services/TecnicoService.java
  src/main/java/com/api/helpr/services/UserDetailsServiceImpl.java
  src/main/resources/application.properties
Labels: documentation, enhancement

#80 Adição do sistema de login com uso de Authorization Token.
  src/main/java/com/api/helpr/config/SecurityConfig.java
  src/main/java/com/api/helpr/domain/dtos/CredenciaisDTO.java
  src/main/java/com/api/helpr/security/JWTAuthenticationFilter.java
  src/main/java/com/api/helpr/security/JWTUtil.java
  src/main/java/com/api/helpr/services/UserDetailsServiceImpl.java
Labels: documentation, enhancement

#81 Método no JwtUtils e classe de Authorization Filter
  src/main/java/com/api/helpr/security/JWTAuthorizationFilter.java
  src/main/java/com/api/helpr/security/JWTUtil.java
  src/main/java/com/api/helpr/services/UserDetailsServiceImpl.java
Labels: documentation, enhancement

#82 Adição das notações de filtros de Autorização de endpoints.
  MySQL/script_helpr/log_pessoa_gt.sql
  src/main/java/com/api/helpr/config/SecurityConfig.java
  src/main/java/com/api/helpr/resources/TecnicoResource.java
  src/main/java/com/api/helpr/services/DBService.java
  src/main/resources/application.properties
Labels: documentation, enhancement

#83 Alterações em chamado e cliente filtro de POST e PUT contrrole da API
  src/main/java/com/api/helpr/resources/ChamadoResource.java
  src/main/java/com/api/helpr/resources/ClienteResource.java
Labels: documentation, enhancement

#89 Relatorio de chamados abertos do cliente #88
  src/main/java/com/api/helpr/repositories/ChamadoRepository.java
  src/main/java/com/api/helpr/resources/ChamadoResource.java
  src/main/java/com/api/helpr/services/ChamadoService.java
Labels: bug, documentation, enhancement

#92 Deploy nas propriedades do Heroku de perfil de DEV
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
Labels: documentation, enhancement

#121 Criada trigger de Log Alteracao prioridades
  MySQL/script_helpr/tg_log_chamado_prioridade.sql
Labels: documentation

#123 Imp de encoder JWT no update de Técnico e Cliente
  src/main/java/com/api/helpr/services/ClienteService.java
  src/main/java/com/api/helpr/services/TecnicoService.java
Labels: bug

#124 Conversão da Query do ChamadoRepository para Procedure
  MySQL/script_helpr/sps_tarefas_encerradas_cliente_semanal.sql
  src/main/java/com/api/helpr/repositories/ChamadoRepository.java
Labels: documentation, enhancement

#127 Proc para rel semanal encerradas pelo cliente
  MySQL/script_helpr/proc_rel_semanal_encerradas_cliente.sql
Labels: documentation, enhancement

#130 Criação da Proc de chamado para status de técnico [60 pts]
  MySQL/script_helpr/proc_chamado_status_tecnico.sql
Labels: enhancement

#131 Procedure de chamados em andamento por técnicos. [45 pts]
  MySQL/script_helpr/sps_tecnicos_andamento.sql
  src/main/java/com/api/helpr/repositories/ChamadoRepository.java
Labels: documentation, enhancement

#132 Procedure Relatório Status data inicial e final
  MySQL/script_helpr/sps_relatorio_status.sql
Labels: documentation, enhancement

#135 relatório de update de perfil de Cliente para Tecnico.
  MySQL/script_helpr/tg_log_chamado_Perfil.sql
Labels: bug, enhancement

#137 Relatório de Status Logs no Chamado [60 pts]
  src/main/java/com/api/helpr/repositories/ChamadoRepository.java
  src/main/java/com/api/helpr/resources/ChamadoResource.java
  src/main/java/com/api/helpr/services/ChamadoService.java
Labels: documentation, enhancement

#138 Montagem do relatório dos Chamados abertos e em andamento
  MySQL/script_helpr/sps_relatorio_chamado_aberto_andamento.sql
  src/main/java/com/api/helpr/repositories/ChamadoRepository.java
  src/main/java/com/api/helpr/resources/ChamadoResource.java
  src/main/java/com/api/helpr/services/ChamadoService.java
Labels: documentation, enhancement

#139 Criação de domínio, serviço e recurso para entregar ao front log de exclusão de técnicos [30 pts]
  src/main/java/com/api/helpr/domain/LogTecnicoExclusao.java
  src/main/java/com/api/helpr/repositories/LogTecnicoExclusaoRepository.java
  src/main/java/com/api/helpr/resources/TecnicoResource.java
  src/main/java/com/api/helpr/services/TecnicoService.java
Labels: documentation, enhancement

#140 Correção do catalogo de importação do TecnicoService.
  src/main/java/com/api/helpr/services/TecnicoService.java
Labels: bug

#141 procedure relatorio chamados abertos por dia
  MySQL/script_helpr/sps_chamados_abertos_soma_dia_tecnico.sql
  src/main/java/com/api/helpr/repositories/ChamadoRepository.java
Labels: documentation, enhancement

#142 Montagem domínio serviço recurso Chamado Prioridade [45pts]
  src/main/java/com/api/helpr/domain/LogChamadoPrioridade.java
  src/main/java/com/api/helpr/repositories/LogChamadoPrioridadeRepository.java
  src/main/java/com/api/helpr/resources/ChamadoResource.java
  src/main/java/com/api/helpr/services/ChamadoService.java
Labels: documentation, enhancement

#143 Endpoint de pessoa para validar perfil [120 pts]
  src/main/java/com/api/helpr/domain/dtos/PessoaDTO.java
  src/main/java/com/api/helpr/resources/PessoaResource.java
  src/main/java/com/api/helpr/services/PessoaService.java
Labels: documentation, enhancement

#147 Endpoint Entrega Chamados encerrados hoje tecnicos - [90 pts]
  MySQL/script_helpr/sp_rel_chamados_enc_hoje_tecnicos.sql
  src/main/java/com/api/helpr/repositories/ChamadoRepository.java
  src/main/java/com/api/helpr/resources/ChamadoResource.java
  src/main/java/com/api/helpr/services/ChamadoService.java
Labels: documentation, enhancement

#155 Criação de domain para futuros clientes
  src/main/java/com/api/helpr/domain/ClienteFuturo.java
Labels: documentation, enhancement

#156 Proc de Tarefas Semanais encerradas de técnico
  MySQL/script_helpr/proc_relatorio_semanal_tecnico.sql
Labels: documentation, enhancement

#159 Filtro de Chamados por título
  MySQL/script_helpr/sps_chamado_titulo.sql
  src/main/java/com/api/helpr/repositories/ChamadoRepository.java
  src/main/java/com/api/helpr/resources/ChamadoResource.java
  src/main/java/com/api/helpr/services/ChamadoService.java
Labels: documentation, enhancement

#160 Criação Candidatos domain,
  src/main/java/com/api/helpr/domain/Candidato.java
  src/main/java/com/api/helpr/domain/dtos/CandidatoDTO.java
  src/main/java/com/api/helpr/repositories/CandidatoRepository.java
  src/main/java/com/api/helpr/resources/CandidatoResource.java
  src/main/java/com/api/helpr/services/CandidatoService.java
  src/main/java/com/api/helpr/services/DBService.java
Labels: enhancement

#163 Criação de método para busca de tecnicos por nome [45pts]
  MySQL/script_helpr/sps_tecnicos_nomes.sql
  src/main/java/com/api/helpr/repositories/TecnicoRepository.java
  src/main/java/com/api/helpr/resources/TecnicoResource.java
  src/main/java/com/api/helpr/services/TecnicoService.java
Labels: documentation, enhancement

#164 Endpoint de busca por nome do candidato
  MySQL/script_helpr/sps_candidato_byNome.sql
  src/main/java/com/api/helpr/repositories/CandidatoRepository.java
  src/main/java/com/api/helpr/resources/CandidatoResource.java
  src/main/java/com/api/helpr/services/CandidatoService.java
Labels: documentation, enhancement
